export const languages = [
  { id: 'id', name: 'Bahasa Indonesia', native: 'Indonesia' },
  { id: 'en', name: 'English', native: 'English' },
  { id: 'jv', name: 'Jawa', native: 'Boso Jowo' },
  { id: 'su', name: 'Sunda', native: 'Basa Sunda' },
  { id: 'ms', name: 'Melayu', native: 'Bahasa Melayu' },
  { id: 'min', name: 'Minangkabau', native: 'Baso Minang' },
  { id: 'bug', name: 'Bugis', native: 'Basa Ugi' },
  { id: 'ban', name: 'Bali', native: 'Basa Bali' },
  { id: 'ace', name: 'Aceh', native: 'Bahsa Acèh' },
  { id: 'mad', name: 'Madura', native: 'Basa Madura' },
  { id: 'bjn', name: 'Banjar', native: 'Bahasa Banjar' },
  { id: 'sas', name: 'Sasak', native: 'Basa Sasak' },
  { id: 'mak', name: 'Makassar', native: 'Basa Mangkasara' },
  { id: 'bat', name: 'Batak', native: 'Hata Batak' },
  { id: 'day', name: 'Dayak', native: 'Bahasa Dayak' },
  { id: 'pap', name: 'Papua', native: 'Bahasa Papua' },
  { id: 'mnd', name: 'Manado', native: 'Bahasa Manado' },
  { id: 'amb', name: 'Ambon', native: 'Bahasa Ambon' },
  { id: 'tew', name: 'Ternate', native: 'Bahasa Ternate' },
  { id: 'nia', name: 'Nias', native: 'Li Niha' },
  { id: 'lamp', name: 'Lampung', native: 'Bahasa Lampung' },
  { id: 'gor', name: 'Gorontalo', native: 'Bahasa Hulontalo' },
  { id: 'tor', name: 'Toraja', native: 'Basa Toraya' },
  { id: 'pal', name: 'Palembang', native: 'Baso Palembang' },
  { id: 'bet', name: 'Betawi', native: 'Bahage Betawi' }
];

export const translations: Record<string, any> = {
  id: {
    heroTag: "Partner AI Pribadi Anda",
    heroTitle: "Kenalan sama",
    heroDesc: "Teman AI yang cepat & cerdas untuk percakapan pintar dan jawaban instan.",
    startChat: "Mulai Chatting",
    seeDemo: "Lihat Demo",
    navHome: "Beranda",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Harga",
    workspaceTitle: "Ruang Kerja Maria",
    workspaceDesc: "Lingkungan AI khusus Anda",
    backHome: "Kembali ke Beranda",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Percakapan",
    inputPlaceholder: "Tanya apa saja ke Maria...",
  },
  en: {
    heroTag: "Your Personal AI Partner",
    heroTitle: "Meet",
    heroDesc: "Your fast & intelligent AI companion for smart conversations and instant answers.",
    startChat: "Start Chatting",
    seeDemo: "See Demo",
    navHome: "Home",
    navFeatures: "Features",
    navHow: "How it works",
    navPricing: "Pricing",
    workspaceTitle: "Maria Workspace",
    workspaceDesc: "Your dedicated AI environment",
    backHome: "Back to Home",
    systemActive: "SYSTEM ACTIVE",
    live: "LIVE",
    streamTitle: "Conversational Stream",
    inputPlaceholder: "Ask Maria anything...",
  },
  jv: {
    heroTag: "Kanca AI Pribadimu",
    heroTitle: "Kenalan karo",
    heroDesc: "Kanca AI sing cepet lan pinter kanggo obrolan lan jawaban sing cepet.",
    startChat: "Mulai Ngobrol",
    seeDemo: "Deleng Demo",
    navHome: "Omah",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Rega",
    workspaceTitle: "Papan Kerja Maria",
    workspaceDesc: "Papan AI khusus kanggo kowé",
    backHome: "Bali menyang Omah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Obrolan",
    inputPlaceholder: "Takon apa wae menyang Maria...",
  },
  su: {
    heroTag: "Mitra AI Pribadi Anjeun",
    heroTitle: "Tepang sareng",
    heroDesc: "Babaturan AI anu gancang & calakan pikeun obrolan sareng waleran instan.",
    startChat: "Ngawitan Ngobrol",
    seeDemo: "Tingali Demo",
    navHome: "Imah",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Harga",
    workspaceTitle: "Rohangan Gawé Maria",
    workspaceDesc: "Lingkungan AI khusus pikeun anjeun",
    backHome: "Balik deui",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Obrolan",
    inputPlaceholder: "Naros naon waé ka Maria...",
  },
  min: {
    heroTag: "Kawan AI Pribadi Sanak",
    heroTitle: "Kenalan jo",
    heroDesc: "Kawan AI yang capek & pantiang untuak carito dan jawek yang instan.",
    startChat: "Mulai Chating",
    seeDemo: "Caliak Demo",
    navHome: "Rumah",
    navFeatures: "Fitur",
    navHow: "Caro Kerjo",
    navPricing: "Harago",
    workspaceTitle: "Ruang Karajo Maria",
    workspaceDesc: "Lingkungan AI khusus untuak sanak",
    backHome: "Baliak ka Rumah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Carito",
    inputPlaceholder: "Tanyo apo se ka Maria...",
  },
  bug: {
    heroTag: "Sella AI Pribaditta",
    heroTitle: "Siddi Maria",
    heroDesc: "Sella AI maccana nennia mapaccé untu addekka nennia pappébali nappé.",
    startChat: "Mappammula Mangobrol",
    seeDemo: "Ita Demo",
    navHome: "Bola",
    navFeatures: "Fitur",
    navHow: "Laleng Jamang",
    navPricing: "Alli-alli",
    workspaceTitle: "Onrong Jamang Maria",
    workspaceDesc: "Onrong AI khusus untu itawa",
    backHome: "Lisun ri Bola",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Arung Obrolang",
    inputPlaceholder: "Makkutana aga-aga ri Maria...",
  },
  ban: {
    heroTag: "Sawitra AI Pribadi Idéwan",
    heroTitle: "Kenalan sareng",
    heroDesc: "Sawitra AI sane gelis & wicaksana anggén maorta-orta sareng nyautin dabdab.",
    startChat: "Ngawit Maorta",
    seeDemo: "Icing Demo",
    navHome: "Umah",
    navFeatures: "Fitur",
    navHow: "Cara Geginan",
    navPricing: "Aji",
    workspaceTitle: "Genah Makarya Maria",
    workspaceDesc: "Genah AI khusus antuk idéwan",
    backHome: "Mabali ka Umah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Alur Maorta",
    inputPlaceholder: "Metaken napa ja ka Maria...",
  },
  ace: {
    heroTag: "Rakan AI Pribadi Gata",
    heroTitle: "Turi ngon",
    heroDesc: "Rakan AI nyang bagah & carong keu peugah haba ngon jaweub nyang lincah.",
    startChat: "Phon Habat",
    seeDemo: "Kalon Demo",
    navHome: "Rumoh",
    navFeatures: "Fitur",
    navHow: "Cara Keureuja",
    navPricing: "Harga",
    workspaceTitle: "Meunasah Keureuja Maria",
    workspaceDesc: "Teumpat AI khusus keu gata",
    backHome: "Gisa u Rumoh",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Haba Peugah",
    inputPlaceholder: "Tanyong peu mantöng bak Maria...",
  },
  mad: {
    heroTag: "Kanca AI Pribadi Ponapa",
    heroTitle: "Kenalan klaban",
    heroDesc: "Kanca AI se lekkas & penter kaangguy acaca klaban jabuwen se lekkas.",
    startChat: "Molae Acaca",
    seeDemo: "Abas Demo",
    navHome: "Roma",
    navFeatures: "Fitur",
    navHow: "Lakon",
    navPricing: "Arga",
    workspaceTitle: "Kennengngan Alako Maria",
    workspaceDesc: "Kennengngan AI khusus kaangguy ponapa",
    backHome: "Mole ka Roma",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aluran Acaca",
    inputPlaceholder: "Atanya ponapa saos ka Maria...",
  },
  bjn: {
    heroTag: "Kawal AI Pribadi Pian",
    heroTitle: "Bakulihan lawan",
    heroDesc: "Kawal AI nang hancap & harat sagan bapandiran wan jawapan lakas.",
    startChat: "Mulai Pandir",
    seeDemo: "Ilihi Demo",
    navHome: "Rumah",
    navFeatures: "Fitur",
    navHow: "Cara Gawe",
    navPricing: "Haraga",
    workspaceTitle: "Wadah Begawi Maria",
    workspaceDesc: "Wadah AI khusus gasan pian",
    backHome: "Bulik ka Rumah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Pandiran Hancap",
    inputPlaceholder: "Takuni apa haja lawan Maria...",
  },
  bet: {
    heroTag: "Sobbat AI Pribadi Ente",
    heroTitle: "Kenalan ame",
    heroDesc: "Sobbat AI nyang cepet & pinter buat ngobrol ame jawaban nyang instan.",
    startChat: "Mulai Ngobrol",
    seeDemo: "Liat Demo",
    navHome: "Rumah",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Harga",
    workspaceTitle: "Tempat Gawe Maria",
    workspaceDesc: "Lingkungan AI khusus buat ente",
    backHome: "Balik ke Rumah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Ngobrol",
    inputPlaceholder: "Tanya apa aje ke Maria...",
  },
  pal: {
    heroTag: "Kawan AI Pribadi Kamu",
    heroTitle: "Kenalan samo",
    heroDesc: "Kawan AI yang cepet & pinter buat ceritoan samo jawaban yang instan.",
    startChat: "Mulai Ngobrol",
    seeDemo: "Inget Demo",
    navHome: "Rumah",
    navFeatures: "Fitur",
    navHow: "Caro Gawe",
    navPricing: "Harago",
    workspaceTitle: "Ruang Gawe Maria",
    workspaceDesc: "Wadah AI khusus buat kamu",
    backHome: "Balik ka Rumah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Cerito",
    inputPlaceholder: "Tanyo apo bae samo Maria...",
  },
  sas: {
    heroTag: "Batur AI Pribadi Side",
    heroTitle: "Kenalan bareng",
    heroDesc: "Batur AI nang sepete & pinter lek bebaos kance jawaban nang selakes.",
    startChat: "Mulai Membaos",
    seeDemo: "Gitaq Demo",
    navHome: "Bale",
    navFeatures: "Fitur",
    navHow: "Cara Gawe",
    navPricing: "Aji",
    workspaceTitle: "Langan Gawe Maria",
    workspaceDesc: "Langan AI khusus lek side",
    backHome: "Uliiq ke Bale",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Baosan Berurutan",
    inputPlaceholder: "Metaun ape bae lek Maria...",
  },
  mak: {
    heroTag: "Balla AI Pribaditta",
    heroTitle: "Siddi Maria",
    heroDesc: "Balla AI maccana nania mapaccé ri bicara nania pappébali nappé.",
    startChat: "Pa'mula Abbicara",
    seeDemo: "Cini' Demo",
    navHome: "Balla",
    navFeatures: "Fitur",
    navHow: "Lalang Jama",
    navPricing: "Alli",
    workspaceTitle: "Onrong Jama Maria",
    workspaceDesc: "Onrong AI khusus ri katte",
    backHome: "Lampa ri Balla",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Arung Bicara",
    inputPlaceholder: "Makkutana apa-apa ri Maria...",
  },
  bat: {
    heroTag: "Dongan AI Pribadi Hamu",
    heroTitle: "Tandaon ma",
    heroDesc: "Dongan AI na hatop dohot na pistar laho marhata dohot alus na tongon.",
    startChat: "Mula Manghatai",
    seeDemo: "Bereng Demo",
    navHome: "Jabu",
    navFeatures: "Fitur",
    navHow: "Dalan Karejo",
    navPricing: "Arga",
    workspaceTitle: "Inganan Karejo Maria",
    workspaceDesc: "Inganan AI khusus di hamu",
    backHome: "Mulak tu Jabu",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Panghataion",
    inputPlaceholder: "Sungkun ma aha pe tu Maria...",
  },
  day: {
    heroTag: "Kawal AI Pribadi Ikau",
    heroTitle: "Kenalan dengan",
    heroDesc: "Kawal AI nang jake & pintar sagan bapandir dan jawapan nang lakas.",
    startChat: "Mulai Bapandir",
    seeDemo: "Ite Demo",
    navHome: "Humah",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Harga",
    workspaceTitle: "Wadah Bagawi Maria",
    workspaceDesc: "Wadah AI khusus sagan ikau",
    backHome: "Buli ka Humah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Alur Bapandir",
    inputPlaceholder: "Paun apa kah dengan Maria...",
  },
  pap: {
    heroTag: "Kawan AI Pribadi Ko",
    heroTitle: "Kenalan deng",
    heroDesc: "Kawan AI yang cepat & pintar buat bicara dan jawaban yang langsung.",
    startChat: "Mulai Bicara",
    seeDemo: "Liat Demo",
    navHome: "Rumah",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Harga",
    workspaceTitle: "Tempat Kerja Maria",
    workspaceDesc: "Tempat AI khusus buat ko",
    backHome: "Pulang ke Rumah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Bicara",
    inputPlaceholder: "Tanya apa saja ka Maria...",
  },
  mnd: {
    heroTag: "Teman AI Pribadi Pa Ngana",
    heroTitle: "Baku dapa deng",
    heroDesc: "Teman AI yang capat & pintar fafia bakusedu deng jawaban yang lancar.",
    startChat: "Mulai Bakusedu",
    seeDemo: "Liat Demo",
    navHome: "Rumah",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Harga",
    workspaceTitle: "Wadah Kerja Maria",
    workspaceDesc: "Wadah AI khusus pa ngana",
    backHome: "Pole ka Rumah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Bakuhaba",
    inputPlaceholder: "Tanya apa saja pa Maria...",
  },
  amb: {
    heroTag: "Temang AI Pribadi Sako",
    heroTitle: "Kenalan deng",
    heroDesc: "Temang AI yang capat & pintar par bacarita deng jawaban yang lancar.",
    startChat: "Mulai Bacarita",
    seeDemo: "Lia Demo",
    navHome: "Rumah",
    navFeatures: "Fitur",
    navHow: "Cara Kerja",
    navPricing: "Harga",
    workspaceTitle: "Tempat Kerja Maria",
    workspaceDesc: "Wadah AI khusus par sako",
    backHome: "Bale ka Rumah",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Alur Bacarita",
    inputPlaceholder: "Tanya apa saja par Maria...",
  },
  tew: {
    heroTag: "Sefo AI Pribadi Ngofa",
    heroTitle: "Dadi deng",
    heroDesc: "Sefo AI yang cepate & pintere par bicara deng jawaban yang lincah.",
    startChat: "Mulahi Bicara",
    seeDemo: "Ite Demo",
    navHome: "Fola",
    navFeatures: "Fitur",
    navHow: "Lalangka Karaja",
    navPricing: "Harga",
    workspaceTitle: "Onrong Karaja Maria",
    workspaceDesc: "Onrong AI khusus par ngofa",
    backHome: "Foli ka Fola",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Bicara",
    inputPlaceholder: "Metoa apa-apa par Maria...",
  },
  nia: {
    heroTag: "Awö AI Nibini'öu",
    heroTitle: "Fahuwu khö",
    heroDesc: "Awö AI si sökhi ba si manari ba wamalua huhuo ba fangombakha hulu.",
    startChat: "Börögö Huhuo",
    seeDemo: "Faigi Demo",
    navHome: "Omo",
    navFeatures: "Fitur",
    navHow: "Lala Wohalöwö",
    navPricing: "Böli",
    workspaceTitle: "Nahia Wohalöwö Maria",
    workspaceDesc: "Nahia AI si sökhi khöu",
    backHome: "Fuli ba Omo",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Huhuo si Manari",
    inputPlaceholder: "Sofu hadia ia khö Maria...",
  },
  lamp: {
    heroTag: "Kanca AI Pribadi Niku",
    heroTitle: "Kenalan jama",
    heroDesc: "Kanca AI sai geluk & pinter guwai nyerito jama jawaban sai hancap.",
    startChat: "Mulai Nyerito",
    seeDemo: "Liyat Demo",
    navHome: "Mahan",
    navFeatures: "Fitur",
    navHow: "Cara Gawi",
    navPricing: "Harga",
    workspaceTitle: "Wadah Gawi Maria",
    workspaceDesc: "Wadah AI khusus guwai niku",
    backHome: "Makhul ke Mahan",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aliran Nyerito",
    inputPlaceholder: "Tanyau api gaweh jama Maria...",
  },
  gor: {
    heroTag: "Dalala AI Pribadi Odito",
    heroTitle: "Tombulia wolo",
    heroDesc: "Dalala AI u mo'amahu & mointu'o paralu potombulu u mopolanggai.",
    startChat: "Tumulai Motombulu",
    seeDemo: "Bilehe Demo",
    navHome: "Bele",
    navFeatures: "Fitur",
    navHow: "Lalangu Kalaja",
    navPricing: "Araga",
    workspaceTitle: "Huta Kalaja Maria",
    workspaceDesc: "Huta AI khusus ode odito",
    backHome: "Mohuli ode Bele",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Aluru Motombulu",
    inputPlaceholder: "Tingohu u hitua-tua ode Maria...",
  },
  tor: {
    heroTag: "Dongan AI Pribadi Kamu",
    heroTitle: "Kenalan sola",
    heroDesc: "Dongan AI maccana sola pinter la kada-kada sola pébali melo.",
    startChat: "Pa'mula Kada-kada",
    seeDemo: "Tiro Demo",
    navHome: "Banua",
    navFeatures: "Fitur",
    navHow: "Lalang Jamang",
    navPricing: "Alli",
    workspaceTitle: "Onrong Jamang Maria",
    workspaceDesc: "Onrong AI khusus sola kamu",
    backHome: "Lampa ri Banua",
    systemActive: "SISTEM AKTIF",
    live: "LANGSUNG",
    streamTitle: "Arung Kada",
    inputPlaceholder: "Makkutana apa-apa sola Maria...",
  }
};
